spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:~/testdb;MODE=MSSQLServer
    username: sa
    password:
    driver: org.h2.Driver
    driver-class-name: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect
    hikari:
      maximumPoolSize: 50
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2
odata:
  update:
    require-id: false
  entitymodel: com.sdl.odata.jpa.model
  odatanamespace: Sdl.Model

  base-path: '^.*\/jpa\/api\/data\/v8.1'